#exception handling

# x = 5
# y = "hello"
# try:
#     z = x + y
# except TypeError:
#     print("Error: cannot add an int and a str")
    
    
    
    
# a = [1, 2, 3]
# try: 
#     print ("Second element = %d" %(a[1]))
    
#     print ("Fourth element = %d" %(a[3]))

# except:
#     print ("An error occurred")





# try: 
#     raise NameError("Hi there")
# except NameError:
#     print ("An exception")
#     raise